const editionData = {
  2024: {
    year: '2024', theme: 'Corpi in libertà', date: '18–19 maggio 2024', accent: 'pink',
    intro: 'Due giornate di talk, workshop e laboratori esperienziali per aprire un dialogo onesto su sessualità, identità e desiderio.',
    photo: 'assets/edizione-2024/copertina-evento.jpg',
    program: [
      { day: 'Giorno 1', time: '09:30 – 10:00', title: 'Apertura evento', people: [{ name: 'Maximiliano Ulivieri', role: 'Diversity Manager del Comune di Bologna · Docente Università di Milano-Bicocca e 24ORE Business School · Ideatore LoveGiver e formatore OEAS.', photo: 'assets/edizione-2024/maximiliano-apertura.jpg' }], description: [`Inizia la giornata con un caloroso benvenuto e una panoramica degli obiettivi dell’evento, stabilendo il tono per un’esperienza trasformativa. Presenta il nostro Deus ex machina.`] },
      { time: '10:05 – 11:05', title: 'Il “comune” senso del pudore', people: [{ name: 'Roberto Rospigliosi', role: 'Psicologo e sessuologo clinico. Si occupa di educazione affettiva e sessuale, con particolare attenzione al corpo, al pudore e alle dinamiche culturali e sociali.', photo: 'assets/edizione-2024/roberto-rospigliosi.jpg' }], description: [`Il pudore è un tema complesso ed ha un ruolo importante nella vita individuale, relazionale e sociale. La gestione del senso del pudore si trasforma a seconda del contesto culturale, storico e individuale: rifletteremo insieme su come questo influenza il rapporto con il corpo, la sessualità e le nostre emozioni.`] },
      { time: '11:10 – 12:10', title: 'Sessualità e diversità', people: [{ name: 'Lukas Romano', role: 'Attivista e formatore sui temi delle identità e degli orientamenti sessuali. Promuove una cultura del rispetto delle differenze e dei diritti.', photo: 'assets/edizione-2024/lukas-romano.jpg' }], description: [`Comprendere le varie identità e orientamenti. L’importanza della comprensione e dell’accettazione delle diverse identità sessuali e orientamenti.`] },
      { time: '12:15 – 13:15', title: 'Laboratorio: comunicazione e consenso', label: 'Laboratorio', people: [{ name: 'Anna Castagna', role: 'Psicologa e sessuologa. Si occupa di educazione affettiva e sessuale, comunicazione, consenso e dinamiche relazionali.', photo: 'assets/edizione-2024/anna-castagna.jpg' }], description: [`Un workshop interattivo focalizzato su come costruire una comunicazione efficace e rispettosa nel contesto della sessualità.`] },
      { time: '14:30 – 15:30', title: 'Sex Toys: conoscenza e piacere', people: [{ name: 'Ivano e Morena · Le Sex en Rose', role: 'Divulgatori e formatori sulla sessualità positiva e consapevole.', photo: 'assets/edizione-2024/sex-toys-panel.jpg' }, { name: 'Fabrizio Quattrini', role: 'Psicologo, psicoterapeuta e sessuologo clinico. Si occupa di educazione sessuale, relazioni e benessere psicologico.' }], description: [`Una sessione interattiva che combina un talk informativo sull’uso dei sex toys per arricchire la vita sessuale, seguito da un workshop pratico su come utilizzare i sex toys in modo sicuro e piacevole.`], gallery: ['assets/edizione-2024/sex-toys/01.jpg', 'assets/edizione-2024/sex-toys/02.jpg', 'assets/edizione-2024/sex-toys/03.jpg', 'assets/edizione-2024/sex-toys/04.jpg', 'assets/edizione-2024/sex-toys/05.jpg'] },
      { time: '15:30 – 16:30', title: 'Intimate Swing, la sedia a dondolo che cambia le prospettive!', people: [{ name: 'Danilo Ragona', role: 'Designer e innovatore nel campo dell’accessibilità. Co-fondatore di Able to Enjoy, sviluppa soluzioni che uniscono mobilità, autonomia e libertà di movimento.', photo: 'assets/edizione-2024/danilo-ragona.jpg' }], description: [`Vita sessuale e conoscenza di sé, consapevolezza delle proprie capacità e potenzialità espressive, cognitive e pragmatiche.`], gallery: ['assets/edizione-2024/intimate-swing/01.jpg', 'assets/edizione-2024/intimate-swing/02.jpg', 'assets/edizione-2024/intimate-swing/03.jpg'] },
      { time: '16:30 – 17:30', title: 'Sessualità e disabilità: sfide e opportunità', label: 'Tavola rotonda', people: [{ name: 'Maximiliano Ulivieri', role: 'Diversity Manager e ideatore di LoveGiver.', photo: 'assets/edizione-2024/maximiliano-ulivieri.jpg' }, { name: 'Fabrizio Quattrini', role: 'Psicologo, psicoterapeuta e sessuologo clinico.' }], description: [`Una discussione aperta sulle sfide uniche e le opportunità nel campo della sessualità quando coinvolge persone con disabilità.`], gallery: ['assets/edizione-2024/sessualita-disabilita/01.jpg', 'assets/edizione-2024/sessualita-disabilita/02.jpg', 'assets/edizione-2024/sessualita-disabilita/03.jpg', 'assets/edizione-2024/sessualita-disabilita/04.jpg'] },
      { time: '17:30 – 19:30', title: 'Una dis-abilità', label: 'Laboratorio esperienziale', people: [{ name: 'Anna Castagna', role: 'Psicologa e sessuologa.', photo: 'assets/edizione-2024/anna-castagna.jpg' }], description: [`Questo workshop avrà lo scopo — giocando — di entrare in contatto con il mondo della disabilità fisica provando sulla propria pelle cosa significa “non poter”.`, `Non poter vedere, non potersi muovere, non poter parlare. Questa esperienza immersiva verrà fatta tramite l’utilizzo dei sensi, calati in diverse situazioni di scambio con l’altro.`, `Ognuno pescherà una “disabilità” e vivrà l’esperienza di entrare in contatto con l’altrə “non potendo”: portando avanti compiti assegnati, aiutando l’altra persona nel limite della disabilità assegnata e facendosi aiutare.`] },
      { time: '17:30 – 19:30', title: 'BDSM', label: 'Laboratorio esperienziale', people: [{ name: 'Ayzad', role: 'Il principale esperto di sesso insolito in Italia.', photo: 'assets/edizione-2024/tei-giunta.png' }], description: [`Laboratorio esplorativo sul mondo del BDSM e le sue varie pratiche.`, `La cronaca racconta ogni giorno la mancanza di consenso e rispetto all’interno delle coppie. Un approccio diverso però esiste: basta prendere esempio dalle regole di cura reciproca sviluppate dalla cultura BDSM, utili per tuttə.`, `Tra rappresentazione mediatica e realtà dei giochi erotici di dominazione e sottomissione, il laboratorio permette di sperimentare strumenti relazionali nati nella cultura kinky ma utilissimi per qualunque coppia: safeword, negoziazione e aftercare.`] },
      { day: 'Giorno 2', time: '10:30 – 11:30', title: 'Esplorazione erotica controcorrente', label: 'Laboratorio', people: [{ name: 'Tei Giunta', role: 'Educatrice e consulente sessuale, sex blogger e autrice di narrativa erotica.', photo: 'assets/edizione-2024/tei-giunta/ritratto.jpg' }], description: [`Un workshop per imparare a godersi il piacere generato da stimoli che spesso non vengono considerati, uscendo dalla genitalità per gioire del potenziale che ogni corpo possiede.`], gallery: ['assets/edizione-2024/tei-giunta/01.jpg', 'assets/edizione-2024/tei-giunta/02.jpg', 'assets/edizione-2024/tei-giunta/03.jpg', 'assets/edizione-2024/tei-giunta/04.jpg'] },
      { time: '11:35 – 12:35', title: 'Disability Hard', people: [{ name: 'Max Ulivieri presenta Nemesi', role: 'Presentazione del progetto “Disability Hard”.', photo: 'assets/edizione-2024/proudence-baelish.png' }], description: [`Portare corpi non conformi all’interno di una realtà come quella della pornografia, da sempre dominata dagli stereotipi estetici tradizionali, può portare un segnale forte da scuotere anche il mainstream televisivo e cinematografico, dove difficilmente c’è spazio e mai corretta rappresentazione delle persone con disabilità.`], gallery: ['assets/edizione-2024/disability-hard/01.jpg', 'assets/edizione-2024/disability-hard/02.jpg', 'assets/edizione-2024/disability-hard/03.jpg', 'assets/edizione-2024/disability-hard/04.jpg', 'assets/edizione-2024/disability-hard/05.jpg', 'assets/edizione-2024/disability-hard/06.jpg'] },
      { time: '12:40 – 13:40', title: 'Bondage tra donne', people: [{ name: 'Proudence Baelish', role: 'Performer, Kinky Advisor e attivista del collettivo KinkyGirls®.', photo: 'assets/edizione-2024/bondage-tra-donne/ritratto.jpg' }], description: [`Scorci di Kinky Girls: bondage tra donne.`, `Bondage tra donne è una performance che utilizza il linguaggio del bondage come forma di comunicazione corporea e relazione consapevole. Al centro non c’è la spettacolarizzazione, ma il consenso, la fiducia e la scelta reciproca tra corpi femminili che si incontrano fuori dallo sguardo normativo.`, `Il gesto del legare diventa atto simbolico e politico, capace di raccontare dinamiche di potere condiviso, cura e responsabilità emotiva. La performance invita il pubblico a osservare senza voyeurismo, mettendo in discussione stereotipi legati al BDSM e aprendo una riflessione sul desiderio come spazio libero, intenzionale e autodeterminato.`], gallery: ['assets/edizione-2024/bondage-tra-donne/01.jpg', 'assets/edizione-2024/bondage-tra-donne/02.jpg', 'assets/edizione-2024/bondage-tra-donne/03.jpg', 'assets/edizione-2024/bondage-tra-donne/04.jpg', 'assets/edizione-2024/bondage-tra-donne/05.jpg', 'assets/edizione-2024/bondage-tra-donne/06.jpg', 'assets/edizione-2024/bondage-tra-donne/07.jpg', 'assets/edizione-2024/bondage-tra-donne/08.jpg', 'assets/edizione-2024/bondage-tra-donne/09.jpg'] },
      { time: '14:30 – 15:30', title: 'Non monogamie etiche', people: [{ name: 'Virginia Mancori', role: 'Psicologa clinica.', photo: 'assets/edizione-2024/non-monogamie-etiche/ritratto.jpg' }], description: [`Un’introduzione chiara e accessibile ai modelli relazionali non monogami basati su consenso, trasparenza e responsabilità emotiva. Attraverso esempi concreti e un linguaggio non giudicante, vengono affrontati temi come scambismo e poliamore, distinguendoli da stereotipi e semplificazioni diffuse.`, `L’incontro offre strumenti per comprendere come le non monogamie etiche non siano una negazione del legame o della cura, ma possano rappresentare forme relazionali strutturate, fondate su comunicazione, negoziazione dei confini e rispetto reciproco. Particolare attenzione è dedicata agli aspetti emotivi, alle gelosie, ai bisogni individuali e alla gestione delle dinamiche di potere.`], gallery: ['assets/edizione-2024/non-monogamie-etiche/01.jpg', 'assets/edizione-2024/non-monogamie-etiche/02.jpg', 'assets/edizione-2024/non-monogamie-etiche/03.jpg'] },
      { time: '15:30 – 16:30', title: 'Pornografie alternative', people: [{ name: 'Inside Porn', role: 'Maria Giulia Giulianelli, Giulia Moscatelli e Arianna Quagliotto · collettivo di divulgazione che analizza criticamente la pornografia contemporanea.', photo: 'assets/edizione-2024/pornografie-alternative/ritratto.jpg' }], description: [`Pornografie mainstream VS pornografie alternative. Tabù a confronto.`, `Cosa s’intende per porno mainstream? Come i tabù sessuali vengono messi in scena? Visione di alcuni spezzoni di porno di entrambe le tipologie, domande al pubblico e analisi finale su come i tabù vengono sfruttati o censurati nei due approcci.`], gallery: ['assets/edizione-2024/pornografie-alternative/01.jpg', 'assets/edizione-2024/pornografie-alternative/02.jpg'] },
      { time: '16:30 – 18:30', title: 'Tantra', label: 'Laboratorio', people: [{ name: 'Manar Shakti', role: 'Facilitatrice di tantra, operatrice olistica e bodyworker.', photo: 'assets/edizione-2024/elisabetta-gennaro.png' }], description: [`L’arte di amare: l’arte del tocco sacro. Un viaggio di trasformazione per chi desidera un profondo lavoro su di sé.`, `Un incontro con se stessə e con l’altrə attraverso il corpo, i sensi, le emozioni e l’energia vitale: respirazione, presenza, meditazione, contatto, tocco e massaggio.`, `Uno spazio di apertura del cuore, per attivare l’energia vitale, emotiva e spirituale e imparare a stare nel corpo.`] },
      { time: '16:30 – 18:30', title: 'Mindfulness e sessualità', label: 'Laboratorio', people: [{ name: 'Elisabetta Gennaro', role: 'Psicologa clinica e psicosessuologa italiana.', photo: 'assets/edizione-2024/elisabetta-gennaro.jpg' }], description: [`Il workshop combina teoria e pratica per esplorare come la presenza mentale possa arricchire l’esperienza sessuale.`, `Dopo un’introduzione alla relazione tra mindfulness e sessualità, seguono esercizi di respirazione e scansione corporea per centrare l’attenzione e aumentare la consapevolezza sensoriale.`, `La parte pratica esplora tocco e sensazioni, individualmente o in coppia, con l’obiettivo di ridurre l’ansia e aprirsi a una sessualità più consapevole. Si chiude con domande, riflessioni e strumenti concreti per la quotidianità.`] }
    ]
  },
  2025: {
    year: '2025', theme: 'Linguaggio, corpi e confini', date: '24–25 maggio 2025', accent: 'coral',
    intro: 'Un viaggio tra parole, desideri e possibilità: due giorni per sfidare gli stereotipi con strumenti, storie e presenza.',
    photo: 'Foto%20NOTABOO/Ridimensionate/notaboo%20016.JPG',
    program: [
      ['10:05', 'Sesso e umorismo: che oscenità!', 'Roberto Rospigliosi', 'Quando ridiamo, qualcosa dentro si rompe: e a volte è proprio ciò che ci impediva di goderci la vita.'],
      ['11:10', 'Hold Me While I’m Naked', 'Beatrice Favaretto · Allison Grimaldi Donahue', 'Fantasie anonime, letture dal vivo e scrittura per cambiare prospettiva sull’erotismo.'],
      ['12:15', 'Consenso, corpo e confini', 'Elisabetta Gennaro', 'Dal BDSM alla quotidianità: negoziazione, limiti e aftercare per relazioni più consapevoli.'],
      ['14:30', 'Transgender', 'Alessia Nobile', 'Autodeterminazione, identità e il coraggio di costruire la propria libertà.'],
      ['15:30', 'Dolore e piacere', 'Anna Castagna · Eleonora Felisatti', 'Riconoscere i segnali, sfatare i miti, ritrovare una sessualità più serena.'],
      ['16:30', 'Progetto DISEX', 'Sara Balducci', 'Sessualità e disabilità cognitiva: storie, formazione e possibilità concrete.'],
      ['17:30', 'Laboratori esperienziali', 'Daphne Rara · Vittoria Hell · Chiara Bacchinelli', 'Automassaggio, gioco, contatto e consenso in spazi accompagnati.'],
      ['Giorno 2', 'Evoluzione nella sessualità', 'Ayzad · Danilo Ragona · Tei Giunta', 'Un secondo giorno di conversazioni e pratiche oltre le convenzioni.']
    ]
  },
  2026: {
    year: '2026', theme: 'Corpi diversi, desideri veri', date: 'Edizione 2026 · Bologna', accent: 'acid',
    intro: 'Un nuovo capitolo dell’archivio NoTaboo: corpi plurali, immaginari radicali e il diritto di desiderare in libertà.',
    photo: 'assets/home/copertina-2026.png',
    program: [
      ['Talk', 'Dolore e piacere: il sesso cucito su misura', 'Mary Agata Sangalli', 'Parlare di dolore, desiderio e benessere con competenza, ascolto e zero fatalismi.'],
      ['Laboratorio', 'Io ti vedo', 'Dalila De Luca', 'Corpo, nudità e immagine fotografica come strumenti di introspezione, relazione e libertà.'],
      ['Esperienza', 'Corpo consapevole', 'Anna Albertarelli', 'Un invito ad abitare sensazioni, presenza e dialogo con il proprio corpo.'],
      ['Pratica', 'Trattamenti sensoriali', 'Daphne Rara', 'Uno spazio guidato per rallentare, sentire e riconnettersi alle proprie percezioni.'],
      ['Incontro', 'Mindfulness e intimità', 'Grattineria', 'Consapevolezza, curiosità e una conversazione più gentile con il desiderio.'],
      ['Ospite', 'Corpi e desideri', 'Ester Cardella', 'Una prospettiva personale e collettiva sulle possibilità dell’espressione.']
    ]
  }
};

const themeUrl = window.noTabooTheme?.url?.replace(/\/$/, '') || '';
const themeAsset = (path) => {
  if (!path || /^(?:https?:|data:|\/\/)/i.test(path)) return path;
  return themeUrl ? `${themeUrl}/${path.replace(/^\//, '')}` : path;
};
const officialLogo = themeAsset('assets/brand/logo-notaboo.png');

// Nel prototipo statico questi fogli non sono nel markup iniziale. Nel tema
// WordPress sono invece già caricati da functions.php: evitarne un secondo
// caricamento con un URL relativo, che nelle pagine /edizione-xxxx/ darebbe 404.
if (!themeUrl) {
  ['brand.css', 'typography.css', 'deployment.css'].forEach((stylesheet) => {
    const style = document.createElement('link');
    style.rel = 'stylesheet';
    style.href = stylesheet;
    document.head.append(style);
  });
}
const favicon = document.querySelector('link[rel~="icon"]') || document.createElement('link');
favicon.rel = 'icon';
favicon.type = 'image/png';
favicon.href = officialLogo;
if (!favicon.parentNode) document.head.append(favicon);
document.querySelectorAll('.brand-mark').forEach((mark) => {
  const logo = document.createElement('img');
  logo.className = 'brand-logo';
  logo.src = officialLogo;
  logo.alt = '';
  mark.replaceWith(logo);
});

const P2025 = 'assets/edizione-2025/wordpress/';
const P2026 = 'assets/edizione-2026/';
editionData[2025].photo = `${P2025}NT043.jpg`;
editionData[2025].intro = 'Due giornate di talk, workshop e laboratori esperienziali per aprire un dialogo onesto su sessualità, identità e desiderio, in un contesto sicuro e accogliente.';
editionData[2025].program = [
  { day: 'Giorno 1', time: '09:30 – 10:00', title: 'Apertura evento', people: [{ name: 'Maximiliano Ulivieri', role: 'Diversity Manager del Comune di Bologna · Docente presso l’Università di Milano-Bicocca e la 24ORE Business School · Ideatore del progetto LoveGiver e formatore OEAS.', photo: 'assets/edizione-2025/wordpress/19052024-DSC_4208.jpg' }], description: ['Inizia la giornata con un caloroso benvenuto e una panoramica degli obiettivi dell’evento, stabilendo il tono per un’esperienza trasformativa. Presenta il nostro Deus ex machina.'] },
  { time: '10:05 – 11:05', title: 'Sesso e umorismo: che oscenità!', people: [{ name: 'Roberto Rospigliosi', role: 'Psicologo e sessuologo clinico. Si occupa di educazione affettiva e sessuale, con particolare attenzione alle dinamiche emotive, culturali e sociali legate al corpo e al pudore.', photo: `${P2025}NT116.jpg` }], description: ['Ridere di sesso non è solo divertente, è anche profondamente sovversivo. L’umorismo ha il potere di smontare tabù, rimescolare le carte del pudore e farci inciampare in nuove prospettive. Ma cosa rende qualcosa sensuale o comico? Il contesto è tutto: un dettaglio può trasformare l’erotico in grottesco o il trasgressivo in ridicolo.', 'Attraverso un viaggio tra cultura, società e percezione del desiderio, esploreremo come la risata possa trasformare l’imbarazzo in conoscenza, la vergogna in libertà e le rigidità in possibilità. Perché quando ridiamo, qualcosa dentro di noi si rompe e a volte, è proprio ciò che ci impediva di goderci la vita.'], gallery: [`${P2025}NT024.jpg`, 'assets/edizione-2025/roberto-03.jpg'] },
  { time: '11:10 – 12:10', title: 'Hold Me While I’m Naked', people: [{ name: 'Beatrice Favaretto', role: 'Artista.' }, { name: 'Allison Grimaldi Donahue', role: 'Poeta.', photo: `${P2025}NT028.jpg` }], description: ['Un progetto artistico nato nel 2020 che esplora la sessualità attraverso la raccolta anonima di fantasie erotiche, presentate al pubblico con letture dal vivo della figura mutevole di Miele.', 'Dopo la prima tappa a Milano nel 2024 con MYSS KETA, arriva a Bologna per Notaboo con eventi interattivi, discussioni collettive e un laboratorio di scrittura per stimolare una riflessione libera sull’erotismo e abbattere i tabù.'], gallery: ['assets/edizione-2025/hold-me-02.jpg', 'assets/edizione-2025/hold-me-03.jpg'] },
  { time: '12:15 – 13:15', title: 'Consenso, corpo e confini. Dal BDSM alla quotidianità.', people: [{ name: 'Elisabetta Gennaro', role: 'Psicologa e psicosessuologa.', photo: 'assets/edizione-2025/elisabetta-gennaro-ritratto.jpg' }], description: ['Consenso, negoziazione, limiti e aftercare sono elementi fondamentali in ogni relazione, ancora più rilevanti quando si parla di sessualità e tabù. Approfondiremo insieme come il corpo comunichi i propri confini, come ascoltarli e comprenderli in modo autentico, distinguendo tra consenso verbale e non verbale.', 'Esploreremo le dinamiche relazionali e le strategie di negoziazione, applicabili sia alla vita quotidiana che al gioco. Si parlerà delle fasi del gioco, dell’importanza dell’aftercare e di come creare spazi sicuri e rispettosi, in cui esprimersi con libertà e consapevolezza.'], gallery: ['assets/edizione-2025/elisabetta-gennaro-02.jpg', 'assets/edizione-2025/elisabetta-gennaro-03.jpg'] },
  { time: '14:30 – 15:30', title: 'Transgender', people: [{ name: 'Alessia Nobile', role: 'Attivista transgender e laureata in Scienze Sociali. Impegnata nella lotta per i diritti umani e contro la violenza, sostiene le persone marginalizzate per promuovere uguaglianza e inclusione. Ha pubblicato il libro “La bambina invisibile”.', photo: `${P2025}CleanShot-2026-01-25-at-13.04.23@2x.png` }], description: ['Alessia è una donna transgender e il suo intervento esplora il percorso di consapevolezza e autodeterminazione nell’identità di genere. Racconta la sua esperienza di crescita, la lotta contro la solitudine e il conformismo, e il cammino verso la transizione, che ha messo in discussione rapporti familiari e sociali.', 'Il suo contributo si concentra sul valore della conoscenza di sé, sul superamento delle barriere culturali e sull’importanza di uno spazio sicuro per l’espressione personale.'] },
  { time: '15:30 – 16:30', title: 'Dolore e piacere: il sesso cucito su misura', people: [{ name: 'Anna Castagna', role: 'Psicologa · Educatrice sessuale · Sessuologa clinica.' }, { name: 'Eleonora Felisatti', role: 'Ostetrica, riabilitatrice del pavimento pelvico, consulente sessuale in formazione.', photo: 'assets/edizione-2025/dolore-piacere/NT013.jpg' }], description: ['Il dolore durante i rapporti sessuali non è sempre normale e soprattutto non è destino. Può avere un impatto profondo sul benessere individuale e di coppia.', 'In questo talk, una sessuologa e un’ostetrica guideranno un confronto aperto su come riconoscere i segnali del dolore fisico ed emotivo, quando è il momento di rivolgersi a un professionista e come ritrovare il piacere. Approfondiremo il legame tra dolore e piacere nella sessualità, sfatando miti e offrendo strumenti pratici per vivere un’intimità più serena e appagante.'], gallery: ['assets/edizione-2025/dolore-piacere/NT014.jpg'] },
  { time: '16:30 – 17:30', title: 'Progetto DISEX: sessualità e disabilità cognitiva, tra storie e possibilità.', people: [{ name: 'Sara Balducci', role: 'Consulente pedagogica e formatrice con più di vent’anni di esperienza in contesti socio-educativi, scolastici e privati. Consulente ed educatrice sessuale.', photo: `${P2025}NT160.jpg` }], description: ['Un lavoro decennale che, attraverso la formazione, il sostegno pedagogico ed educativo, ha accompagnato centinaia di professionisti, famiglie e persone con disabilità cognitiva in un percorso volto a promuovere pratiche e relazioni sessuali e affettive, il più possibili consapevoli, autodeterminate e rispettose.', 'Oltre gli stereotipi e le fragilità, un’educazione sessuale e affettiva realmente per tutt3.'], gallery: [`${P2025}NT039.jpg`] },
  { time: '17:30 – 19:30', title: 'Adora la tua vulva – Automassaggio Yoni', label: 'Laboratorio esperienziale', people: [{ name: 'Daphne Rara', role: 'Self love coach · Sensual arts facilitator.', photo: `${P2025}CleanShot-2026-01-25-at-13.18.44@2x.png` }], description: ['Un laboratorio esperienziale per esplorare e riconnetterti con il tuo spazio sacro. Attraverso Yoni Gazing — osservazione consapevole — una guida anatomica e un automassaggio di gruppo, scoprirai un nuovo modo di ascoltare il tuo corpo, senza aspettative.', 'Non è una pratica masturbatoria, ma un viaggio di scoperta, consapevolezza e amore per sé. Un momento di intimità con te stessa, per sciogliere tensioni e rafforzare il legame con la tua energia vitale.'] },
  { time: '17:30 – 19:30', title: 'BDSM', label: 'Laboratorio esperienziale', people: [{ name: 'Vittoria Hell', role: 'Divulgatrice, consulente e professionista nel mondo della sessualità alternativa.', photo: `${P2025}CleanShot-2026-01-25-at-13.24.25@2x.png` }], description: ['Un workshop coinvolgente che unisce teoria e pratica per guidarti nella creazione di giochi di ruolo erotici memorabili. Imparerai a strutturare una narrazione avvincente, a scegliere personaggi e dinamiche adatte e a costruire un arco evolutivo che amplifichi il coinvolgimento emotivo e sensoriale.', 'Alla fine dell’incontro, avrai gli strumenti per dare vita alle tue fantasie con creatività e consapevolezza.'] },
  { day: 'Giorno 2', time: '10:30 – 11:30', title: 'Sporco', people: [{ name: 'Teresa Sala', role: 'Regista e filmmaker indipendente.' }, { name: 'Pierluigi Lenzi', role: 'Scrittore.', photo: `${P2025}NT051.jpg` }], description: ['Un viaggio alla scoperta di un corpo; la rivendicazione della propria identità. Un’identità vorace, spregiudicata, ebbra di vita, che ricade socialmente sotto l’etichetta “sporca” e come tale è stata vissuta, ma che in quello sporco ha trovato la propria libertà.'], gallery: [`${P2025}NT173.jpg`] },
  { time: '11:35 – 12:35', title: 'Dominazione', people: [{ name: 'Madame Jacqueline Domina', role: 'Sex worker.', photo: 'assets/edizione-2025/dominazione/NT053.jpg' }], description: ['Lei è una Dominatrice, attiva da anni nella scena BDSM e punto di riferimento per chi vive e pratica relazioni basate su consenso, cura e libertà. Parallelamente, è un’attivista impegnata nella lotta per i diritti delle persone che fanno sex work, con l’obiettivo di decostruire lo stigma e portare maggiore consapevolezza sociale e politica su questi temi spesso distorti o ignorati.'], gallery: ['assets/edizione-2025/dominazione/NT054.jpg', 'assets/edizione-2025/dominazione/NT055.jpg', 'assets/edizione-2025/dominazione/NT059.jpg', 'assets/edizione-2025/dominazione/NT052.jpg', 'assets/edizione-2025/dominazione/NT060.jpg', 'assets/edizione-2025/dominazione/NT061.jpg'] },
  { time: '12:40 – 13:40', title: 'O.E.A.S.', people: [{ name: 'Giulia Deiana', role: 'O.E.A.S.' }, { name: 'Fabrizio Quattrini', role: 'Psicologo, psicoterapeuta e sessuologo.', photo: 'assets/edizione-2025/oeas/NT067.jpg' }], description: ['La figura dell’Operatore all’Emotività Affettiva e Sessuale rappresenta un passo rivoluzionario nel riconoscimento del diritto alla sessualità per le persone con disabilità. In questo talk esploreremo il ruolo degli OEAS, il percorso formativo che li qualifica e il loro impatto sulle vite delle persone che necessitano di un supporto per vivere la propria affettività e sessualità in modo più consapevole e autodeterminato.'], gallery: ['assets/edizione-2025/oeas/NT065.jpg', 'assets/edizione-2025/oeas/NT066.jpg'] },
  { time: '14:30 – 15:30', title: 'Evoluzione nella sessualità: come gestirla.', people: [{ name: 'Ayzad', role: 'Studia e insegna sessualità atipiche fin dal secolo scorso. Autore di best-seller sul BDSM e del Manifesto degli Esploratori Sessuali, come coach guida chi nutre desideri erotici non convenzionali a soddisfare le proprie fantasie in modo etico, consapevole e divertente.', photo: 'assets/edizione-2025/ayzad/NT134.jpg' }], description: ['Come è cambiato nel tempo il rapporto con le diversità, specie nel mondo del sesso? Cosa possiamo ancora cambiare, e come? Le esperienze di un “esploratore del sesso insolito” ci condurranno in un viaggio sorprendente oltre tutti i pregiudizi. Anche i nostri.'], gallery: ['assets/edizione-2025/ayzad/NT133.jpg'] },
  { time: '15:30 – 16:30', title: 'Salotto 88 – il video podcast senza tabù', people: [{ name: 'Danilo Ragona', role: 'Designer.', photo: `${P2025}NT140.jpg` }], description: ['Ogni puntata è un tempo di condivisione inclusiva, di dialogo libero e senza pregiudizi dove si parla di sesso e sentimenti in modo autentico, inclusivo e senza ipocrisie. Qui, ogni sensibilità, esperienza e preferenza trova voce in un confronto intimo, ironico e stimolante.', 'Il format accoglie persone di ogni genere, età, cultura e orientamento sessuale, per raccontare tutte le sfumature della sessualità.'], gallery: [`${P2025}NT138.jpg`] },
  { time: '16:30 – 18:30', title: 'Cuddle space', label: 'Laboratorio', people: [{ name: 'Chiara Bacchinelli', role: 'Psicologa, consulente sessuale e facilitatrice.', photo: `${P2025}CleanShot-2026-01-25-at-19.39.52@2x.png` }], description: ['Cuddle space è un laboratorio in cui sperimentare con il contatto fisico e conoscere meglio se stess*. Fai fatica a dire di no? Esprimi liberamente e con chiarezza i tuoi desideri? Ti trovi più spesso a dare o a ricevere? Di cosa hai bisogno per sentirti al sicuro?', 'Attraverso alcuni esercizi di comunicazione potrai allenarti a praticare il consenso e metterti alla prova nel rispetto di te stess* e de* altr*. L’incontro offrirà poi uno spazio in cui condividere momenti di affetto fisico come coccole, abbracci e massaggi.'] },
  { time: '16:30 – 18:30', title: 'Piacere di conoscer(mi)ti', label: 'Laboratorio', people: [{ name: 'Tei Giunta', role: 'Educatrice sessuale, blogger, autrice di narrativa erotica.', photo: `${P2025}CleanShot-2026-01-25-at-19.44.47@2x.png` }], description: ['Il workshop esplora il ruolo della focalizzazione sensoriale nell’esperienza sessuale, combinando teoria e pratica. Spesso, le persone non vengono educate a riconoscere i propri desideri e sensazioni, ma piuttosto a conformarsi a ciò che è considerato “giusto” nelle relazioni intime.', 'Questa mancanza di consapevolezza limita la capacità di desiderare e sperimentare il piacere.'] }
];

editionData[2026] = {
  year: '2026', theme: 'Corpi in libertà', date: '20–21 giugno 2026 · Bologna', accent: 'acid',
  intro: 'Due giornate di talk, laboratori e sessioni individuali per aprire un dialogo libero, competente e rispettoso su sessualità, corpi, relazioni e desiderio.',
  photo: `${P2026}hero_813f8037.png`,
  program: [
    { day: '20 giugno · Talk', time: '09:30 – 10:00', title: 'Apertura dell’evento', people: [{ name: 'Maximiliano Ulivieri', role: 'Diversity Manager · Organizzatore dell’evento', photo: `${P2026}maximiliano_6af68781.jpg` }], description: ['Un benvenuto e una panoramica degli obiettivi dell’evento, con il regolamento che accompagna le due giornate.'] },
    { time: '10:05 – 11:05', title: 'Prova a non essere', people: [{ name: 'Roberto Rospigliosi', role: 'Pedagogista, mediatore familiare, counselor di coppia e individuale', photo: `${P2026}roberto_b9cfe44b.png` }], description: ['Tra protezione e stigma: una riflessione sul processo di identificazione, anche nella sessualità, quando una liberazione può trasformarsi in una nuova norma.', 'Come restare nella tensione degli opposti senza ridurre la complessità dell’esperienza umana a un’etichetta.'] },
    { time: '11:10 – 12:10', title: 'Genitorialità ed educazione sessuale: tra bisogni, tabù e consapevolezza', people: [{ name: 'Sara Balducci', role: 'Consulente pedagogica', photo: `${P2026}sara_8c3e85c8.png` }], description: ['L’educazione sessuale e affettiva permea la vita di ogni persona: non è una lezione di anatomia, ma relazione, autonomia e benessere.', 'Un confronto su ruoli, contesto culturale, ascolto, tutela, comunicazione e rischi di una mancata educazione sessuale.'] },
    { time: '12:10 – 13:10', title: 'A suffering pleasure: un dialogo tra dolore e piacere', people: [{ name: 'Mary Agata Sangalli', role: 'Psicologa clinica e consulente in sessualità', photo: `${P2026}mary_aa65e1a5.png` }], description: ['Come può uno stimolo nocivo trasformarsi in qualcosa di soggettivamente piacevole, sensuale o erotico? Un percorso tra corpo, emozioni, memorie e percezioni.', 'Nelle pratiche BDSM ascolto, fiducia e cura reciproca costruiscono un contesto sicuro, in cui hurt non significa harm.'] },
    { time: '14:30 – 15:30', title: 'Giardino della sessualità', people: [{ name: 'Greta Tosoni', role: 'Consulente, educatrice sessuale e sex coach', photo: `${P2026}greta_e006c325.jpg` }], description: ['Se la sessualità fosse un giardino, quali aree sarebbero rigogliose e quali trascurate? Un viaggio interattivo tra corpo, identità, desiderio e relazioni.', 'Per coltivare la consapevolezza delle nostre unicità e somiglianze.'] },
    { time: '15:30 – 16:30', title: 'Abbastanza bravi a letto?', people: [{ name: 'Anna Castagna', role: 'Psicologa', photo: `${P2026}anna_castagna_1396ef33.jpg` }], description: ['Come le aspettative sul sesso possono trasformare l’intimità in una prestazione da riuscire bene.', 'Una prospettiva psicologica e sessuologica su imperfezione, desiderio, comunicazione e libertà di costruire una sessualità più reale e meno performativa.'] },
    { time: '16:30 – 17:30', title: 'Kinbaku: la dimensione relazionale della corda', people: [{ name: 'Marta Santospirito · MartaTenshiko', role: 'Educatrice sessuale e di kinbaku', photo: `${P2026}marta_14bfcc36.jpg` }], description: ['Un incontro accessibile per avvicinarsi alla corda attraverso corpo, ascolto e relazione. Non una lezione tecnica di legatura, ma un’esplorazione di ritmo, tensione, fiducia e presenza reciproca.'] },
    { time: '17:30 – 19:30', title: 'Body Play / Mind Play', label: 'Laboratorio', people: [{ name: 'Anna Soares', role: 'Divulgatrice BDSM e performer', photo: `${P2026}anna_soares_real_eed3502f.png` }, { name: 'LuciPherd', role: 'Storyteller e formatore sulla cultura BDSM', photo: `${P2026}lucipherd_a63a54ad.png` }], description: ['Un laboratorio tra gioco del corpo e gioco della mente nelle dinamiche di potere BDSM: contatto, sguardo, piacere, dolore, percezione e connessione.', 'Beginner friendly: ogni attività è proposta in un contesto sicuro e consensuale, senza obbligo di partecipazione.'] },
    { time: '17:30 – 19:30', title: 'IO TI VEDO — Laboratorio per anime (coraggiose) nude', label: 'Laboratorio', people: [{ name: 'Dalila De Luca', role: 'Fotografa esperienziale', photo: `${P2026}dalila_de_luca_98d46e55.jpg` }], description: ['Un laboratorio di contatto, ritualità, movimento e immagine fotografica per sperimentare una comunicazione oltre le parole, in un clima di fiducia e non giudizio.', 'Il laboratorio si svolge integralmente nudi; ogni contatto è non sessuale e fondato su consenso, rispetto e accoglienza.'] },
    { day: '21 giugno · Talk', time: '10:00 – 10:30', title: 'Apertura seconda giornata', people: [{ name: 'Maximiliano Ulivieri', role: 'Diversity Manager · Organizzatore', photo: `${P2026}maximiliano_6af68781.jpg` }], description: ['Presentazione della seconda giornata, dei laboratori e delle esperienze in programma.'] },
    { time: '10:30 – 11:15', title: 'Poesia', people: [{ name: 'Serena Vestene', role: 'Scrittrice · Pittrice · OEAS', photo: `${P2026}serena_bc27b9de.png` }], description: ['La poesia come chiave di avvicinamento comunicativo ed empatico: metafora, allegoria e poesia erotica per risvegliare immaginazione, emozioni e desiderio.'] },
    { time: '11:15 – 12:15', title: 'La bocca che sente: piacere, voce e sessualità', people: [{ name: 'Simona Spinoglio', role: 'Psicologa, educatrice professionale, counselor', photo: `${P2026}simona_1f604b60.jpg` }], description: ['La bocca del piacere, del desiderio, del contatto e dell’intimità. Voce, respiro e suono come forme di relazione corporea, anche nei contesti di disabilità e medicalizzazione.'] },
    { time: '12:15 – 13:15', title: 'Diritti, non salvezza: cosa vogliono le sex worker', people: [{ name: 'Grace', role: 'Sex worker · Attivista', photo: `${P2026}grace_7481ec0b.jpeg` }], description: ['Le voci delle persone che fanno sex work, spesso ignorate nel dibattito pubblico: decriminalizzazione, riduzione della violenza, dei rischi e dell’isolamento.', 'Sarà possibile proporre domande anonime.'] },
    { time: '14:30 – 15:30', title: 'Porno-rivoluzione: i protagonisti del cambiamento', people: [{ name: 'Il Mima', role: 'Pornoattore', photo: `${P2026}il_mima_76ab16a3.jpeg` }, { name: 'Nemesi Widow', role: 'Pornoattrice', photo: `${P2026}nemesi_a67eea3f.jpeg` }, { name: 'Ines Alma Latina', role: 'Pornoattrice', photo: `${P2026}ines_a5c05146.jpeg` }], description: ['Cosa accade quando al centro della pornografia entrano corpi non conformi, bisogni specifici e possibilità diverse?', 'Esperienze dirette per mettere in crisi gli standard dominanti e aprire lo spazio a una sessualità più vera, varia e meno patinata.'] },
    { time: '15:30 – 16:30', title: 'L’arte del burlesque', people: [{ name: 'Jazz Chimera', role: 'Artista burlesque', photo: `${P2026}jazz_3aefbff0.png` }], description: ['Mein Herr: un act dal musical Cabaret. In un club della Berlino degli anni ’30, Sally Bowles porta sul palco una sensualità selvatica, cresciuta in cattività.'] },
    { time: '16:30 – 18:30', title: 'Orgia Vestita', label: 'Laboratorio', people: [{ name: 'Tei Giunta', role: 'Consulente relazionale, educatrice sessuale e ADHD coach', photo: `${P2026}tei_d3c427d2.jpeg` }], description: ['Un viaggio erotico che parte dalla mente per arrivare al corpo: fantasie, focalizzazione sensoriale, embodiment, consenso, contatto e role playing in un contesto guidato e sicuro.', 'Per esplorare i desideri in modo esplicito e consapevole, superando imbarazzi e copioni limitanti.'] },
    { time: '16:30 – 18:30', title: 'Corpo Poetico® — Ricerca per altri movimenti', label: 'Laboratorio', people: [{ name: 'Anna Albertarelli', role: 'Formatrice, acting dance coach, coreografa', photo: `${P2026}anna_albertarelli_3ac41601.png` }], description: ['Un laboratorio esperienziale sulla consapevolezza e la libertà corporea, con strumenti della danza contemporanea e del teatro fisico.', 'Attivazione percettiva, movimento, espressività, ascolto non verbale e cooperazione: non sono richieste esperienze precedenti.'] },
    { day: 'Sessioni private · 20–21 giugno', time: 'Su prenotazione', title: 'Tantra & Touch Sexual Healing', label: 'Sessione privata', people: [{ name: 'Manar Shakti', role: 'Yogini, Tāntrika, bodyworker e operatrice olistica', photo: `${P2026}manar-shakti_3d4db054.jpeg` }], description: ['Sessioni individuali di ascolto profondo del corpo: respiro, presenza, tocco consapevole e ascolto emozionale per favorire consapevolezza e autoguarigione.', 'Uno spazio fondato sul rispetto dei confini personali, del consenso e della sensibilità di ogni persona.'] },
    { time: 'Su prenotazione · circa 10 min', title: 'Experience Breve della Grattineria', label: 'Sessione privata', people: [{ name: 'La Grattineria', role: 'Trattamento multisensoriale · ASMR · regolazione del sistema nervoso', photo: `${P2026}grattineria_practitioner_ac9ef89d.jpeg` }], description: ['Un trattamento multisensoriale breve: grattini leggeri nella parte alta del corpo, audio ASMR in cuffia, tocco, suono e rallentamento.', 'Una pausa dal sovraccarico quotidiano per fermarsi, respirare e riconnettersi con sé stessi.'], gallery: [`${P2026}grattineria_session_1c1cd488.jpeg`] },
    { day: 'Ospite speciale', time: 'Durante il festival', title: 'Ester Cardella', label: 'Ospite speciale', people: [{ name: 'Ester Cardella', role: 'Fumettista erotica indipendente', photo: `${P2026}ester_cardella_a89b82cf.jpg` }], description: ['Fumettista indipendente di genere erotico con sfumature dark. Le sue donne, audaci e sensuali, parlano di autodeterminazione e libertà.'] },
    { time: 'Durante il festival', title: 'Presentatrice del Festival', label: 'Host', people: [{ name: 'Lecicia Sorri', role: 'Presentatrice del Festival', photo: `${P2026}lecicia_sorri_21e4cafa.jpeg` }], description: ['La voce che accompagna le due giornate di NoTaboo Festival 2026.'] }
  ]
};

function editionPage() {
  const year = document.body.dataset.edition || new URLSearchParams(window.location.search).get('year');
  const e = editionData[year];
  if (!e) return;
  if ((year === '2025' || year === '2026') && !document.querySelector('link[href="edition-2024.css"]')) {
    const archiveStyles = document.createElement('link');
    archiveStyles.rel = 'stylesheet';
    archiveStyles.href = themeAsset('edition-2024.css');
    document.head.append(archiveStyles);
  }
  if (!document.querySelector('link[href="multi-speakers.css"]')) {
    const groupStyles = document.createElement('link');
    groupStyles.rel = 'stylesheet';
    groupStyles.href = themeAsset('multi-speakers.css');
    document.head.append(groupStyles);
  }
  if (!document.querySelector('link[href="navigation.css"]')) {
    const navigationStyles = document.createElement('link');
    navigationStyles.rel = 'stylesheet';
    navigationStyles.href = themeAsset('navigation.css');
    document.head.append(navigationStyles);
  }
  document.title = `NoTaboo ${e.year} — ${e.theme}`;
  document.querySelector('[data-year]').textContent = e.year;
  document.querySelector('[data-theme]').textContent = e.theme;
  document.querySelector('[data-date]').textContent = e.date;
  document.querySelector('[data-intro]').textContent = e.intro;
  document.querySelector('[data-hero-image]').style.backgroundImage = `url("${themeAsset(e.photo)}")`;
  if (year === '2025') {
    document.querySelector('.gallery-one').style.backgroundImage = `url("${themeAsset('assets/edizione-2025/finale-notaboo.jpg')}")`;
    document.querySelector('.gallery-one').style.gridColumn = 'span 2';
    document.querySelector('.gallery-two').style.display = 'none';
    document.querySelector('.next-edition .button--acid').style.color = 'var(--ink)';
  }
  if (year === '2026') {
    document.querySelector('.gallery-one').style.backgroundImage = `url("${themeAsset(`${P2026}hero_813f8037.png`)}")`;
    document.querySelector('.gallery-two').style.backgroundImage = `url("${themeAsset(`${P2026}grattineria_session_1c1cd488.jpeg`)}")`;
    document.querySelector('.next-edition .button--acid').style.color = 'var(--ink)';
  }
  if (year === '2024') {
    document.querySelector('.gallery-one').style.backgroundImage = `url("${themeAsset('assets/edizione-2024/finale-pubblico.jpg')}")`;
    document.querySelector('.gallery-one').style.gridColumn = 'span 2';
    document.querySelector('.gallery-two').style.display = 'none';
    document.querySelector('.next-edition .button--acid').style.color = 'var(--ink)';
    const video = document.createElement('section');
    video.className = 'edition-video';
    video.innerHTML = '<div class="edition-video__copy"><p class="eyebrow">NoTaboo 2024 · da vedere</p><h2>GUARDA<br /><em>L’EDIZIONE.</em></h2><p>Un frammento vivo di corpi, voci e possibilità condivise.</p></div><div class="edition-video__frame"><iframe src="https://www.youtube-nocookie.com/embed/IiTj37u-pN8?rel=0" title="NoTaboo 2024" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>';
    document.querySelector('.edition-hero').after(video);
    const videoStyles = document.createElement('style');
    videoStyles.textContent = '.edition-video{align-items:center;background:#121212;color:#fff;display:grid;gap:7vw;grid-template-columns:minmax(240px,.58fr) minmax(0,1.15fr);padding:88px 9vw}.edition-video__copy .eyebrow{color:var(--acid);margin:0 0 16px}.edition-video__copy h2{font:700 clamp(3.2rem,5.8vw,6.2rem)/.85 var(--space);letter-spacing:-.09em;margin:0}.edition-video__copy h2 em{color:var(--coral);font-style:normal}.edition-video__copy>p:last-child{color:#d7d1cb;font-size:15px;line-height:1.5;max-width:260px;margin:25px 0 0}.edition-video__frame{background:#000;border:1px solid rgba(255,255,255,.2);box-shadow:16px 16px 0 var(--coral);line-height:0;overflow:hidden}.edition-video__frame iframe{aspect-ratio:16/9;border:0;display:block;width:100%}@media(max-width:760px){.edition-video{display:block;padding:63px 23px}.edition-video__copy{margin-bottom:33px}.edition-video__copy h2{font-size:3.5rem}.edition-video__frame{box-shadow:9px 9px 0 var(--coral)}}';
    document.head.append(videoStyles);
  }
  document.querySelector('[data-program]').innerHTML = e.program.map((item, index) => {
    if (Array.isArray(item)) return `<article class="program-item"><div class="program-time">${item[0]}</div><div><p class="program-index">${String(index + 1).padStart(2,'0')}</p><h3>${item[1]}</h3><p class="program-guest">${item[2]}</p><p class="program-description">${item[3]}</p></div><span class="program-symbol">✦</span></article>`;
    const day = item.day ? `<p class="program-day">${item.day}</p>` : '';
    const label = item.label ? `<p class="program-label">${item.label}</p>` : '';
    const portraitPeople = item.people.filter(person => person.photo);
    const portraits = portraitPeople.map(person => `<img src="${themeAsset(person.photo)}" alt="${person.name}" loading="lazy" />`).join('');
    const portraitClass = portraitPeople.length > 1 ? `speaker-portraits speaker-portraits--group speaker-portraits--${portraitPeople.length}` : 'speaker-portraits';
    const people = item.people.map(person => `<div class="speaker"><h4>${person.name}</h4><p>${person.role}</p></div>`).join('');
    const description = item.description.map(text => `<p>${text}</p>`).join('');
    const gallery = item.gallery?.length ? `<div class="event-gallery"><p class="gallery-label">Dentro l’incontro</p><div class="gallery-grid">${item.gallery.map((photo, photoIndex) => { const image = themeAsset(photo); return `<button type="button" class="gallery-image" data-gallery-src="${image}" aria-label="Apri foto ${photoIndex + 1} di ${item.title}"><img src="${image}" alt="Momento dal talk ${item.title}" loading="lazy" /></button>`; }).join('')}</div></div>` : '';
    return `${day}<article class="program-item program-item--full"><div class="program-time">${item.time}</div><div class="program-full-content"><p class="program-index">${String(index + 1).padStart(2,'0')}</p>${label}<h3>${item.title}</h3><div class="program-full-body${portraits ? '' : ' no-portrait'}"><div class="${portraitClass}">${portraits}</div><div><div class="speaker-list">${people}</div><div class="program-description">${description}</div>${gallery}</div></div></div><span class="program-symbol">✦</span></article>`;
  }).join('');
}

document.querySelector('#year')?.append(new Date().getFullYear());
editionPage();
const header = document.querySelector('.site-header');
const updateHeaderState = () => header?.classList.toggle('is-scrolled', window.scrollY > 40);
updateHeaderState();
window.addEventListener('scroll', updateHeaderState, { passive: true });
const menu = document.querySelector('.menu-button');
menu?.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') === 'true'; menu.setAttribute('aria-expanded', String(!open)); document.querySelector('.mobile-menu').classList.toggle('is-open'); });
document.querySelectorAll('.mobile-menu a').forEach(link => link.addEventListener('click', () => { menu?.setAttribute('aria-expanded','false'); document.querySelector('.mobile-menu').classList.remove('is-open'); }));
function getLightbox() { let dialog = document.querySelector('.image-lightbox'); if (!dialog) { dialog = document.createElement('dialog'); dialog.className = 'image-lightbox'; dialog.setAttribute('aria-label', 'Foto ingrandita'); dialog.innerHTML = '<button class="lightbox-close" type="button" aria-label="Chiudi foto">×</button><img src="" alt="Foto dell’evento" />'; document.body.append(dialog); } return dialog; }
document.addEventListener('click', (event) => { const trigger = event.target.closest('.gallery-image'); if (!trigger) return; const dialog = getLightbox(); dialog.querySelector('img').src = trigger.dataset.gallerySrc; dialog.showModal(); });
document.addEventListener('click', (event) => { const dialog = document.querySelector('.image-lightbox'); if (dialog && (event.target.closest('.lightbox-close') || event.target === dialog)) dialog.close(); });
const observer = new IntersectionObserver((entries) => entries.forEach(entry => { if (!entry.isIntersecting) return; entry.target.classList.add('is-visible'); observer.unobserve(entry.target); }), { threshold: .12 });
document.querySelectorAll('.edition-card,.values-grid article,.project-card,.faq details,.program-item,.quote-band p').forEach((el, index) => {
  el.classList.add('reveal');
  el.style.setProperty('--reveal-delay', `${(index % 4) * 70}ms`);
  observer.observe(el);
});
requestAnimationFrame(() => {
  document.querySelectorAll('.hero .reveal, .collab-hero .reveal').forEach((el, index) => setTimeout(() => el.classList.add('is-visible'), 150 + index * 130));
});
